version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
    timezone: Australia/Sydney
  open-pull-requests-limit: 99
- package-ecosystem: 'github-actions'
  directory: '/'
  schedule:
    interval: 'weekly'
